controller:
  workflowNamespaces:
    - workflows
server:
  serviceAccount:
    create: true
  extraArgs:
    - server
    - --auth-mode=client
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - /wf(/|$)(.*)