{{- if not .Values.piper.gitProvider.webhook.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "piper.gitProvider.webhook.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.piper.gitProvider.webhook.secret }}
  secret: {{ .Values.piper.gitProvider.webhook.secret | b64enc | quote }}
  {{- else }}
  secret: {{ randAlphaNum 30 | b64enc | quote }}
  {{- end }}
{{- end }}
