piper:
  gitProvider:
    name: github
    token: "GIT_TOKEN"
    organization:
      name: "ORG_NAME"
    webhook:
      url: https://NGROK_ADDRESS/piper/webhook
      orgLevel: false
      repoList: ["REPO_NAME"]
  argoWorkflows:
    server:
      namespace: "workflows"
      address: "ARGO_ADDRESS"
      token: "ARGO_TOKEN"
  workflowsConfig:
    default: |
      spec:
        activeDeadlineSeconds: 7200 # (seconds) == 2 hours
        ttlStrategy:
          secondsAfterCompletion: 28800 # (seconds) == 8 hours
        podGC:
          strategy: OnPodSuccess
      onExit:
        - name: exit-handler
          template: local-step
          arguments:
            parameters:
            - name: message
              value: triggerd from default config
image:
  name: piper
  repository: localhost:5001
  pullPolicy: Always
  tag: latest
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - paths:
        - path: /piper(/|$)(.*)
          pathType: ImplementationSpecific