apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
  labels:
    branch: test-branch
    commit: xxxxxxxxxxxxxx
    repo: somerepo
    user: gosharo
spec:
  volumes:
  - name: shared-volume
    emptyDir: { }
  activeDeadlineSeconds: 7200 # (seconds) == 2 hours
  ttlStrategy:
    secondsAfterCompletion: 28800 # (seconds) == 8 hours
  podGC:
    strategy: OnPodSuccess
  archiveLogs: true
  arguments:
    parameters:
      - name: PLACHOLDER
  artifactRepositoryRef:
    configMap: artifact-repositories
  onExit: exit-handler
  entrypoint: entrypoint
  nodeSelector:
    node_pool: workflows
  serviceAccountName: argo-wf
  tolerations:
    - effect: NoSchedule
      key: node_pool
      operator: Equal
      value: workflows
  templates:
  - dag:
    name: exit-handler
    tasks:
    - name: github-status
      template: exit-handler
      arguments:
        parameters:
        - name: param1
          value: '{{ workflow.labels.repo }}'
  - name: local-step
    inputs:
      parameters:
      - name: message
    script:
      image: alpine
      command: [sh]
      source: |
        echo "wellcome to {{ workflow.parameters.global }}
        echo "{{ inputs.parameters.message }}"
  - name: exit-handler
    script:
      image: alpine
      command: [sh]
      source: |
        echo "exit"
  - dag:
      name: entrypoint
      tasks:
      - name: local-step1
        template: local-step
        arguments:
          parameters:
          - name: message
            value: step-1
      - name: local-step2
        template: local-step
        arguments:
          parameters:
          - name: message
            value: step-2
        dependencies:
        - local-step1
        
        
    