{{- if and .Values.piper.gitProvider.token (not .Values.piper.gitProvider.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "piper.gitProvider.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  token: {{ .Values.piper.gitProvider.token | b64enc | quote }}
{{- end }}
