apiVersion: v1
kind: Service
metadata:
  name: {{ include "piper.fullname" . }}
  labels:
    {{- include "piper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "piper.selectorLabels" . | nindent 4 }}