name: CI
on:
  push:
    branches:
      - "main"
      - "release"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: true
      - run: make test

  piper-image:
    name: piper-image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: rookout/piper:latest
          outputs: type=docker,dest=/tmp/piper_image.tar
          target: piper
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: actions/upload-artifact@v3
        with:
          name: piper
          path: /tmp/piper_image.tar
          if-no-files-found: error
  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
  helm:
    name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Git diff in /helm-chart
        run: |
          if [ "$(git diff --exit-code --name-only --diff-filter=d origin/main -- helm-chart/)" != "" ]; then
            echo "There are Git diffs in the /helm-chart folder."
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          else
            echo "There are no Git diffs in the /helm-chart folder."
          fi
      - name: Helm lint and template
        run: |
          make helm
        if: ${{ env.CHART_UPDATED }}