name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: true
      - run: make test
  e2e-tests:
    name: E2E Tests (on development)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: true
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: localhost:5001/piper:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#      - name: install kind
#        run: |
#          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
#          chmod +x ./kind
#          sudo mv ./kind /usr/local/bin/kind
#      - name: init kind cluster
#        run: |
#          make init-kind
#          make init-nginx
#          make init-argo-workflows
#      - name: Build Docker Image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: localhost:5001/piper:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#      - name: deploy piper
#        run: make init-piper


  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          only-new-issues: true
          skip-pkg-cache: true
  helm:
    name: Helm Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Git diff in /helm-chart
        run: |
          if [ "$(git diff --exit-code --name-only --diff-filter=d origin/main -- helm-chart/)" != "" ]; then
            echo "There are Git diffs in the /helm-chart folder."
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          else
            echo "There are no Git diffs in the /helm-chart folder."
          fi
      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.0
      - name: Helm lint and template
        run: |
          make helm
        if: ${{ env.CHART_UPDATED }}