name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  lint:
    permissions:
      pull-requests: read  # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write  # for amannn/action-semantic-pull-request to mark status of analyzed PR
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          # Configure which types are allowed (newline delimited).
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            feat
            fix
            docs
            chore
            revert
            ci
          # Configure which scopes are allowed (newline delimited).
          scopes: |
            core
            RK-\d+
          # Configure that a scope must always be provided.
          requireScope: false
          ignoreLabels: |
            autorelease: pending
        env:
          GITHUB_TOKEN: ${{ github.token }}
