name: Release Workflow

on:
  release:
    types:
      - published
      - edited

jobs:
  piper-image:
    name: piper-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: rookout/piper:${{ github.ref }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  helm:
    name: helm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "sonario"
          git config user.email "sonario@rookout.com"
      - name: Check Git diff in /helm-chart
        run: |
          if [ "$(git diff --exit-code --name-only --diff-filter=d origin/main -- helm-chart/)" != "" ]; then
            echo "There are Git diffs in the /helm-chart folder."
            echo "CHART_UPDATED=true" >> $GITHUB_ENV
          else
            echo "There are no Git diffs in the /helm-chart folder."
          fi
      - name: Install Helm
        uses: azure/setup-helm@v3
        if: ${{ env.CHART_UPDATED }}
      - name: Helm lint and template
        run: |
          make helm
          helm package ./helm-chart  // need to add signing flags
        if: ${{ env.CHART_UPDATED }}
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          version:  ${{ github.ref }}
          charts_dir: helm-chart
        env:
          CR_TOKEN: ${{ github.token }}