name: Snyk Scan

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
jobs:
  snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version: "1.20"
#          cache: true
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Build Docker Image without push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: rookout/piper:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Snyk Container monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth 
          snyk container monitor rookout/piper:latest --file=Dockerfile
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif